// cyber_Track_FrontEnd/src/app/pages/complaints/social/social.component.ts
import { Component } from '@angular/core';
import { FormGroup , FormBuilder, ReactiveFormsModule, FormsModule} from '@angular/forms';
import { MatInputModule } from '@angular/material/input';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatDatepickerModule } from '@angular/material/datepicker';
import { MatNativeDateModule } from '@angular/material/core'; // Required for datepicker
import { MatIconModule } from '@angular/material/icon';
import { MatLabel } from '@angular/material/form-field';
import { RouterModule, Router } from '@angular/router';

@Component({
  selector: 'app-social',
  standalone: true,
  imports: [RouterModule, MatInputModule, MatFormFieldModule, MatButtonModule, MatCardModule, MatDatepickerModule, MatNativeDateModule, MatIconModule, ReactiveFormsModule, FormsModule],
  templateUrl: './social.component.html',
  styleUrl: './social.component.css'
})
export class SocialComponent {
  complaint:FormGroup;
  constructor(private fb: FormBuilder, private router: Router) {
    this.complaint = this.fb.group({
      id: [''],
      victim_Name: [''],
      date_of_birth: [''],
      address: [''],
      unique_id: [''],
      contact_no: [''],
      contact_email: [''],
      guardian_no: [''],
      description: [''],
      medium: [''],
      evidence_links: [''],
      unique_id_card: [null],
      signature: [null],
      screenshots: [null],
      other_doc: [null],
      status: ['Pending'],
      created_at: [''],
      updated_at: [''],
    });
  }
  onSubmit() {
    console.log(this.complaint.value);
    this.router.navigate(['/success']);

  }
  onFileChange(event: Event, fieldName: string) {
    const input = event.target as HTMLInputElement;
    if (input.files && input.files.length > 0) {
      const file = input.files[0];
      this.complaint.patchValue({
        [fieldName]: file
      });
    }
  }
}

<div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <mat-card>
          <mat-card-header>
            <mat-card-title>
              <h4>Social Complaint Form</h4>
            </mat-card-title>
          </mat-card-header>
          <mat-card-content>
            <form [formGroup]="complaint" (ngSubmit)="onSubmit()">
              
              <!-- Victim Name -->
              <mat-form-field class="full-width" appearance="fill">
                <mat-label>Victim Name</mat-label>
                <input matInput type="text" formControlName="victim_Name">
              </mat-form-field>
  
              <!-- Date of Birth -->
              <mat-form-field class="full-width" appearance="fill">
                <mat-label>Date of Birth</mat-label>
                <input matInput [matDatepicker]="picker" formControlName="date_of_birth">
                <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
                <mat-datepicker #picker></mat-datepicker>
              </mat-form-field>
  
              <!-- Address -->
              <mat-form-field class="full-width" appearance="fill">
                <mat-label>Address</mat-label>
                <input matInput type="text" formControlName="address">
              </mat-form-field>
  
              <!-- Unique ID -->
              <mat-form-field class="full-width" appearance="fill">
                <mat-label>Unique ID</mat-label>
                <input matInput type="text" formControlName="unique_id">
              </mat-form-field>
  
              <!-- Contact No -->
              <mat-form-field class="full-width" appearance="fill">
                <mat-label>Contact No</mat-label>
                <input matInput type="text" formControlName="contact_no">
              </mat-form-field>
  
              <!-- Contact Email -->
              <mat-form-field class="full-width" appearance="fill">
                <mat-label>Contact Email</mat-label>
                <input matInput type="email" formControlName="contact_email">
              </mat-form-field>
  
              <!-- Guardian No -->
              <mat-form-field class="full-width" appearance="fill">
                <mat-label>Guardian No</mat-label>
                <input matInput type="text" formControlName="guardian_no">
              </mat-form-field>
  
              <!-- Description -->
              <mat-form-field class="full-width" appearance="fill">
                <mat-label>Description</mat-label>
                <textarea matInput formControlName="description"></textarea>
              </mat-form-field>
  
              <!-- Medium -->
              <mat-form-field class="full-width" appearance="fill">
                <mat-label>Medium</mat-label>
                <input matInput type="text" formControlName="medium">
              </mat-form-field>
  
              <!-- Evidence Links -->
              <mat-form-field class="full-width" appearance="fill">
                <mat-label>Evidence Links</mat-label>
                <input matInput type="text" formControlName="evidence_links">
              </mat-form-field>
  
              <!-- Unique ID Card (File input) -->
              <div class="form-group">
                <label for="unique_id_card">Unique ID Card</label>
                <input type="file" class="form-control" id="unique_id_card" (change)="onFileChange($event, 'unique_id_card')">
              </div>
  
              <!-- Signature (File input) -->
              <div class="form-group">
                <label for="signature">Signature</label>
                <input type="file" class="form-control" id="signature" (change)="onFileChange($event, 'signature')">
              </div>
  
              <!-- Screenshots (File input) -->
              <div class="form-group">
                <label for="screenshots">Screenshots</label>
                <input type="file" class="form-control" id="screenshots" (change)="onFileChange($event, 'screenshots')">
              </div>
  
              <!-- Other Documents (File input) -->
              <div class="form-group">
                <label for="other_doc">Other Documents</label>
                <input type="file" class="form-control" id="other_doc" (change)="onFileChange($event, 'other_doc')">
              </div>
  
              <!-- Submit Button -->
              <button mat-raised-button color="primary" type="submit">Submit</button>
  
            </form>
          </mat-card-content>
        </mat-card>
      </div>
    </div>
  </div>

// cybertrack-react/src/components/social.js
import React, { useState } from 'react';

export default function Social() {
  const [formData, setFormData] = useState({
    victim_Name: '',
    date_of_birth: '',
    address: '',
    unique_id: '',
    contact_no: '',
    contact_email: '',
    guardian_no: '',
    description: '',
    medium: '',
    evidence_links: '',
    unique_id_card: null,
    signature: null,
    screenshots: null,
    other_doc: null,
  });

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({
      ...formData,
      [name]: value,
    });
  };

  const handleFileChange = (e, fieldName) => {
    setFormData({
      ...formData,
      [fieldName]: e.target.files[0],
    });
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    // Handle form submission logic here
    console.log(formData);
  };

  return (
    <div className="container mt-5">
      <div className="row justify-content-center">
        <div className="col-md-8">
          <div className="card">
            <div className="card-header">
              <h4>Social Complaint Form</h4>
            </div>
            <div className="card-body">
              <form onSubmit={handleSubmit}>
                <div className="form-group">
                  <label>Victim Name</label>
                  <input
                    type="text"
                    className="form-control"
                    name="victim_Name"
                    value={formData.victim_Name}
                    onChange={handleChange}
                    required
                  />
                </div>
                <div className="form-group">
                  <label>Date of Birth</label>
                  <input
                    type="date"
                    className="form-control"
                    name="date_of_birth"
                    value={formData.date_of_birth}
                    onChange={handleChange}
                  />
                </div>
                <div className="form-group">
                  <label>Address</label>
                  <input
                    type="text"
                    className="form-control"
                    name="address"
                    value={formData.address}
                    onChange={handleChange}
                  />
                </div>
                <div className="form-group">
                  <label>Unique ID</label>
                  <input
                    type="text"
                    className="form-control"
                    name="unique_id"
                    value={formData.unique_id}
                    onChange={handleChange}
                  />
                </div>
                <div className="form-group">
                  <label>Contact No</label>
                  <input
                    type="text"
                    className="form-control"
                    name="contact_no"
                    value={formData.contact_no}
                    onChange={handleChange}
                  />
                </div>
                <div className="form-group">
                  <label>Contact Email</label>
                  <input
                    type="email"
                    className="form-control"
                    name="contact_email"
                    value={formData.contact_email}
                    onChange={handleChange}
                  />
                </div>
                <div className="form-group">
                  <label>Guardian No</label>
                  <input
                    type="text"
                    className="form-control"
                    name="guardian_no"
                    value={formData.guardian_no}
                    onChange={handleChange}
                  />
                </div>
                <div className="form-group">
                  <label>Description</label>
                  <textarea
                    className="form-control"
                    name="description"
                    value={formData.description}
                    onChange={handleChange}
                  ></textarea>
                </div>
                <div className="form-group">
                  <label>Medium</label>
                  <input
                    type="text"
                    className="form-control"
                    name="medium"
                    value={formData.medium}
                    onChange={handleChange}
                  />
                </div>
                <div className="form-group">
                  <label>Evidence Links</label>
                  <input
                    type="text"
                    className="form-control"
                    name="evidence_links"
                    value={formData.evidence_links}
                    onChange={handleChange}
                  />
                </div>
                <div className="form-group">
                  <label>Unique ID Card</label>
                  <input
                    type="file"
                    className="form-control"
                    onChange={(e) => handleFileChange(e, 'unique_id_card')}
                  />
                </div>
                <div className="form-group">
                  <label>Signature</label>
                  <input
                    type="file"
                    className="form-control"
                    onChange={(e) => handleFileChange(e, 'signature')}
                  />
                </div>
                <div className="form-group">
                  <label>Screenshots</label>
                  <input
                    type="file"
                    className="form-control"
                    onChange={(e) => handleFileChange(e, 'screenshots')}
                  />
                </div>
                <div className="form-group">
                  <label>Other Documents</label>
                  <input
                    type="file"
                    className="form-control"
                    onChange={(e) => handleFileChange(e, 'other_doc')}
                  />
                </div>
                <button type="submit" className="btn btn-primary mt-3">
                  Submit
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
